/****************************************************************************
 * AnchoBgSrv.idl : IDL source for Ancho background service
 * Copyright 2012 Salsita software (http://www.salsitasoft.com).
 * Author: Arne Seib <kontakt@seiberspace.de>
 ****************************************************************************/

import "oaidl.idl";
import "ocidl.idl";


// forwards
interface IAnchoAddonBackground;
interface IAnchoRuntime;
interface IAnchoServiceApi;

/*==========================================================================*/
[
	object,
	uuid(DA08F068-BA41-431A-94BB-5EB3C46767A2),
	oleautomation,
	nonextensible,
	helpstring("IAnchoAddonService Interface"),
	pointer_default(unique)
]
interface IAnchoAddonService : IUnknown
{
  HRESULT GetAddonBackground([in] BSTR bsID, [out, retval] IAnchoAddonBackground ** ppRet);
  HRESULT GetModulePath([out, retval] BSTR * pbsPath);

  HRESULT registerRuntime([in] INT aFrameTab, [in] IAnchoRuntime * aRuntime, [out, retval] INT *aTabID);
  HRESULT unregisterRuntime([in] INT aTabID);
  HRESULT createTabNotification([in] INT aTabID, [in] INT aRequestID);
  HRESULT invokeEventObjectInAllExtensions([in] BSTR aEventName, [in] LPDISPATCH aArgs);

  HRESULT webBrowserReady();

  HRESULT registerBrowserActionToolbar([in] INT aFrameTab, [out] BSTR * aUrl, [out] INT*aTabId);
  HRESULT unregisterBrowserActionToolbar([in] INT aTabId);
  HRESULT getDispatchObject([out, retval] IDispatch **aRet);
};




/*==========================================================================*/
[
  object,
  uuid(921C5C5B-3353-42d1-B9D3-BE7FFA912F2A),
  oleautomation,
  nonextensible,
  helpstring("IAnchoAddonBackground Interface"),
  pointer_default(unique)
]
interface IAnchoAddonBackground : IUnknown
{
  HRESULT AdviseInstance([out, retval] ULONG * pInstanceID);
  HRESULT UnadviseInstance([in] ULONG ulInstanceID);
  HRESULT GetContentInfo([in] ULONG ulInstanceID, [in] BSTR bstrUrl, [out, retval] LPDISPATCH* ppDisp);
  HRESULT ReleaseContentInfo([in] ULONG ulInstanceID);
//  HRESULT GetManifest([out, retval] LPDISPATCH* ppDisp);
};

/*==========================================================================*/
[
	uuid(E010DD54-F388-4292-9BAE-C962B22F17BD),
	version(1.0),
	helpstring("AnchoBgSrv 1.0 Type Library")
]
library AnchoBgSrvLib
{
  [
    object,
    uuid(6A0B8BBD-48C4-41fc-BE68-E9A1ECB0F83B),
    dual,
    nonextensible,
    pointer_default(unique)
  ]
  interface IAnchoXmlHttpRequest : IDispatch
  {
    [id(0x00000001), helpstring("Open HTTP connection")]
    HRESULT open(
                    [in] BSTR bstrMethod,
                    [in] BSTR bstrUrl,
                    [in, optional] VARIANT varAsync,
                    [in, optional] VARIANT bstrUser,
                    [in, optional] VARIANT bstrPassword);
    [id(0x00000002), helpstring("Add HTTP request header")]
    HRESULT setRequestHeader(
                    [in] BSTR bstrHeader,
                    [in] BSTR bstrValue);
    [id(0x00000003), helpstring("Get HTTP response header")]
    HRESULT getResponseHeader(
                    [in] BSTR bstrHeader,
                    [out, retval] BSTR* pbstrValue);
    [id(0x00000004), helpstring("Get all HTTP response headers")]
    HRESULT getAllResponseHeaders([out, retval] BSTR* pbstrHeaders);
    [id(0x00000005), helpstring("Send HTTP request")]
    HRESULT send([in, optional] VARIANT varBody);
    [id(0x00000006), helpstring("Abort HTTP request")]
    HRESULT abort();
    [id(0x00000007), propget, helpstring("Get HTTP status code")]
    HRESULT status([out, retval] long* plStatus);
    [id(0x00000008), propget, helpstring("Get HTTP status text")]
    HRESULT statusText([out, retval] BSTR* pbstrStatus);
    [id(0x00000009), propget, helpstring("Get response body")]
    HRESULT responseXML([out, retval] IDispatch** ppBody);
    [id(0x0000000a), propget, helpstring("Get response body")]
    HRESULT responseText([out, retval] BSTR* pbstrBody);
    [id(0x0000000b), propget, helpstring("Get response body")]
    HRESULT responseBody([out, retval] VARIANT* pvarBody);
    [id(0x0000000c), propget, helpstring("Get response body")]
    HRESULT responseStream([out, retval] VARIANT* pvarBody);
    [id(0x0000000d), propget, helpstring("Get ready state")]
    HRESULT readyState([out, retval] long* plState);
    [id(0x0000000e), propput, helpstring("Register a complete event handler")]
    HRESULT onreadystatechange([in] IDispatch* rhs);
    [propget]
    HRESULT withCredentials([out, retval] VARIANT* aRet);
  };

  [
    object,
    uuid("14293D7A-EEED-4DBE-A84C-BDBBFEA2882F"),
    dual,
    pointer_default(unique)
  ]
  interface IWebBrowserEventHandler : IDispatch
  {
    [id(DISPID_VALUE)]
    HRESULT onFire();
  };

	importlib("stdole2.tlb");
  [
	  object,
	  uuid(06550FFB-49D7-4428-A5FF-2CC688A8001F),
	  oleautomation,
	  nonextensible,
	  helpstring("IAnchoRuntime Interface"),
	  pointer_default(unique)
  ]
  interface IAnchoRuntime : IUnknown
  {
    HRESULT reloadTab();
    HRESULT closeTab();
    HRESULT executeScript([in] BSTR aExtensionId, [in] BSTR aCode, [in] INT aFileSpecified);
    HRESULT updateTab([in] LPDISPATCH aProperties);
    HRESULT fillTabInfo([in] VARIANT* aInfo);
  };

  /*==========================================================================*/
  [
    object,
    uuid(3442CFB9-7E99-4509-B9E1-854CCD317562),
    dual,
    oleautomation,
    nonextensible,
    helpstring("IAnchoServiceApi Interface"),
    pointer_default(unique)
  ]
  interface IAnchoServiceApi : IDispatch
  {
    [propget, id(1)]
    HRESULT cookieManager([out, retval] LPDISPATCH* ppRet);

    HRESULT createTab([in] LPDISPATCH aProperties, [in] LPDISPATCH aCreator, [in] LPDISPATCH aCallback);
    HRESULT updateTab([in] INT aTabId, [in] LPDISPATCH aProperties);
    HRESULT getTabInfo([in] INT aTabId, [in] LPDISPATCH aCreator, [out, retval] VARIANT* aRet);
    HRESULT removeTabs([in] LPDISPATCH aTabs, [in] LPDISPATCH aCallback);
    HRESULT queryTabs([in] LPDISPATCH aQueryInfo, [in] LPDISPATCH aCreator, [out, retval] VARIANT* aRet);

    HRESULT getWindow([in] INT aWindowId, [in] LPDISPATCH aCreator, [in] BOOL aPopulate, [out, retval] VARIANT* aRet);
    HRESULT getAllWindows([in] LPDISPATCH aCreator, [in] BOOL aPopulate, [out, retval] VARIANT* aRet);
    HRESULT updateWindow([in] INT aWindowId, [in] LPDISPATCH aProperties);
    HRESULT createWindow([in] LPDISPATCH aProperties, [in] LPDISPATCH aCreator, [in] LPDISPATCH aCallback);
    HRESULT closeWindow([in] INT aWindowId);
    HRESULT createPopupWindow([in] BSTR aUrl, INT aX, INT aY, [in] LPDISPATCH aInjectedData, [in] LPDISPATCH aCloseCallback);
    HRESULT getCurrentWindowId([out, retval] INT *aWinId);

    HRESULT executeScript([in] BSTR aExtensionId, [in] INT aTabID, [in] BSTR aCode, [in] BOOL aFileSpecified, [in] BOOL aInAllFrames);
    HRESULT invokeExternalEventObject([in] BSTR aExtensionId, [in] BSTR aEventName, [in] LPDISPATCH aArgs, [out, retval] VARIANT* aRet);

    HRESULT getBrowserActions([out, retval] VARIANT* aBrowserActionsArray);
    HRESULT addBrowserActionInfo([in] LPDISPATCH aBrowserActionInfo);
    HRESULT setBrowserActionUpdateCallback([in] INT aTabId, [in] LPDISPATCH aBrowserActionUpdateCallback);
    HRESULT browserActionNotification();

    HRESULT testFunction([out, retval] IDispatch** ppVal);
  };

  /*==========================================================================*/
  [
    object,
    uuid(0F317CA8-BB88-4141-906F-257DA0603639),
    dual,
    nonextensible,
    pointer_default(unique)
  ]
  interface IIECookie : IDispatch{
    [id(1), propget, helpstring("property name")]
    HRESULT name([out, retval] BSTR * pbsRet);

    [id(2), propget, helpstring("property value")]
    HRESULT value([out, retval] BSTR * pbsRet);

    [id(3), propget, helpstring("property domain")]
    HRESULT domain([out, retval] BSTR * pbsRet);

    [id(4), propget, helpstring("property path")]
    HRESULT path([out, retval] BSTR * pbsRet);

    [id(5), propget, helpstring("property expirationDate")]
    HRESULT expirationDate([out, retval] VARIANT * aRet);
  };

  [
    object,
    uuid(5DB362D1-77BF-49CA-AA1C-9AAA5AA6320F),
    dual,
    nonextensible,
    pointer_default(unique)
  ]
  interface IIECookieManager : IDispatch{
    [id(1), helpstring("enumCookies")]
    HRESULT enumCookies([in] LPDISPATCH pCallback);

    [id(2), helpstring("removeCookie")]
    HRESULT removeCookie([in] BSTR aUrl, [in] BSTR aName);

    [id(3), helpstring("setCookie")]
    HRESULT setCookie([in] BSTR aUrl, [in] BSTR aName, [in] BSTR aData);

    [id(4), helpstring("getCookie")]
    HRESULT getCookie([in] BSTR aUrl, [in] BSTR aName, [out, retval] VARIANT * aRet);
  };


/*==========================================================================*/
  [
	  object,
	  uuid(C501AEAC-8839-4EB5-956A-1826EE6B2FF7),
	  dual,
	  nonextensible,
	  helpstring("IAnchoBackgroundAPI Interface"),
	  pointer_default(unique)
  ]
  interface IAnchoBackgroundAPI : IDispatch
  {
    [propget, id(1), helpstring(
      "Property id. The addon's ID."
    )]
    HRESULT id([out, retval] BSTR * pVal);

    [propget, id(2), helpstring(
      "Property guid. The addon's GUID."
    )]
    HRESULT guid([out, retval] BSTR * pVal);

    [id(100), helpstring(
      "Method startBackgroundWindow. Loads the background window and"
      "runs scripts inside"
    )]
    HRESULT startBackgroundWindow([in] BSTR bsPartialURL);

    HRESULT addEventObject([in]BSTR aEventName, [in] INT aInstanceId, [in] LPDISPATCH aListener);
    HRESULT removeEventObject([in]BSTR aEventName, [in] INT aInstanceId);

    HRESULT invokeEventObject([in] BSTR aEventName, [in] INT aSelectedInstance, [in] BOOL aSkipInstance, [in] LPDISPATCH aArgs, [out, retval] VARIANT* aRet);
    HRESULT invokeEventWithIDispatchArgument([in] BSTR aEventName, [in] LPDISPATCH aArg);
    HRESULT setIDispatchEventInvocationHandler([in] LPDISPATCH aFunction);
    HRESULT callFunction([in] LPDISPATCH aFunction, [in] LPDISPATCH aArgs, [out, retval] VARIANT* aRet);
  };

/*==========================================================================*/
  [
	  helpstring(
      "IAnchoBackgroundConsole interface"
    ),
	  object,
	  uuid(5FF52F47-7CEC-45a9-979F-2F214ACAED1B),
    oleautomation,
    nonextensible,
	  pointer_default(unique)
  ]
  interface IAnchoBackgroundConsole : IUnknown
  {
    [id(1), helpstring(
      "Method log"
    )]
    HRESULT log([in] BSTR bsSource, [in] BSTR bsModuleID, [in] SAFEARRAY(VARIANT) pVals);

    [id(2), helpstring(
      "Method debug"
    )]
    HRESULT debug([in] BSTR bsSource, [in] BSTR bsModuleID, [in] SAFEARRAY(VARIANT) pVals);

    [id(3), helpstring(
      "Method info"
    )]
    HRESULT info([in] BSTR bsSource, [in] BSTR bsModuleID, [in] SAFEARRAY(VARIANT) pVals);

    [id(4), helpstring(
      "Method warn"
    )]
    HRESULT warn([in] BSTR bsSource, [in] BSTR bsModuleID, [in] SAFEARRAY(VARIANT) pVals);

    [id(5), helpstring(
      "Method error"
    )]
    HRESULT error([in] BSTR bsSource, [in] BSTR bsModuleID, [in] SAFEARRAY(VARIANT) pVals);
  };

/*==========================================================================*/
  [
		uuid(2620B92E-09AC-4C35-8164-0BDF33951278),
		helpstring("AnchoAddonService Class")
	]
	coclass AnchoAddonService
	{
		[default] interface IAnchoAddonService;
	};

/*==========================================================================*/
  [
		uuid(EAFE9780-A951-4282-9C8A-39672B406357),
		helpstring("AnchoAddonBackground Class")
	]
	coclass AnchoAddonBackground
	{
		[default] interface IAnchoAddonBackground;
	};

  [
    uuid(91B40A1B-C72A-4887-8C63-036D0649CDDA)
  ]
  coclass IECookie
  {
    [default] interface IIECookie;
  };
  [
    uuid(DE9A7F77-BBCC-4B18-BF38-F9C90262BB6F)
  ]
  coclass IECookieManager
  {
    [default] interface IIECookieManager;
  };

  [
    uuid("495DFDA2-D1CC-4577-9AA1-7623823EF791")
  ]
  coclass AnchoXmlHttpRequest
  {
    [default] interface IAnchoXmlHttpRequest;
  };
};
